# Generated by Django 3.0.4 on 2020-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200924_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='kane-williamson.jpg', null=True, upload_to=''),
        ),
    ]
